[versions]
agp = "8.13.2"
dokka = "2.1.0"
compose = "1.10.0"
kotlin = "2.3.0"
kotlinter = "5.3.0"
android-minSdk = "24"
android-compileSdk = "36"
vanniktech = "0.35.0"

[libraries]

[plugins]
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
